package app.entity;

import java.util.Date;

/**
 * IpTmp generated by MyEclipse Persistence Tools
 */

public class IpTmp implements java.io.Serializable {

	// Fields

	private Integer id;

	private String uid;

	private Float ip;

	private Date date;

	// Constructors

	/** default constructor */
	public IpTmp() {
	}

	/** minimal constructor */
	public IpTmp(String uid, Date date) {
		this.uid = uid;
		this.date = date;
	}

	/** full constructor */
	public IpTmp(String uid, Float ip, Date date) {
		this.uid = uid;
		this.ip = ip;
		this.date = date;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public Float getIp() {
		return this.ip;
	}

	public void setIp(Float ip) {
		this.ip = ip;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}