package app.entity;

import java.util.Date;

/**
 * Logs generated by MyEclipse Persistence Tools
 */

public class Logs implements java.io.Serializable {

	// Fields

	private Integer id;

	private String uid;

	private Date datetime;

	private String something;
	
	private String type;//类型 如系统，vave
	
	private String kind;//种类 删除，登录

	// Constructors

	public Logs( String uid, String something,
			String type, String kind) {
		super();

		this.uid = uid;
		this.datetime = new Date();
		this.something = something;
		this.type = type;
		this.kind = kind;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getKind() {
		return kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	/** default constructor */
	public Logs() {
	}

	/** full constructor */
	public Logs(String uid, Date datetime, String something) {
		this.uid = uid;
		this.datetime = datetime;
		this.something = something;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public String getSomething() {
		return this.something;
	}

	public void setSomething(String something) {
		this.something = something;
	}

}