package app.entity;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;

/**
 * TcompanyIndex generated by MyEclipse Persistence Tools
 */

public class TcompanyIndex  implements java.io.Serializable {

	// Fields

	private Integer id;

	private TindexTarget tindexTarget=new TindexTarget();

	private Tdepartment tdepartment =new Tdepartment();

	private Float score;
	
	private Float percentage;
	
	private Float act_output;
	
	private String output;
	// Constructors

	public String getOutput() {
		DecimalFormat   df   =   new   DecimalFormat("#.0000");   
		return df.format(act_output);
		
	}

	public void setOutput(String output) {
		this.output = output;
	}

	public Float getPercentage() {
		return percentage;
	}

	public void setPercentage(Float percentage) {
		this.percentage = percentage;
	}

	/** default constructor */
	public TcompanyIndex() {
	}

	/** minimal constructor */
	public TcompanyIndex(Integer id, TindexTarget tindexTarget,
			Tdepartment tdepartment) {
		this.id = id;
		this.tindexTarget = tindexTarget;
		this.tdepartment = tdepartment;
	}

	/** full constructor */
	public TcompanyIndex(Integer id, TindexTarget tindexTarget,
			Tdepartment tdepartment, Float score) {
		this.id = id;
		this.tindexTarget = tindexTarget;
		this.tdepartment = tdepartment;
		this.score = score;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TindexTarget getTindexTarget() {
		return this.tindexTarget;
	}

	public void setTindexTarget(TindexTarget tindexTarget) {
		this.tindexTarget = tindexTarget;
	}

	public Tdepartment getTdepartment() {
		return this.tdepartment;
	}

	public void setTdepartment(Tdepartment tdepartment) {
		this.tdepartment = tdepartment;
	}

	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

	public Float getAct_output() {
		return act_output;
	}

	public void setAct_output(Float act_output) {
		this.act_output = act_output;
	}
	
	public static List<TcompanyIndex> copyChangeIndex(List<TcompanyIndex> dpIndexs,Integer indexID)
	{
		List<TcompanyIndex> newDpIndexs=new ArrayList<TcompanyIndex>();
		for(TcompanyIndex dpelem:dpIndexs)
		{
			TcompanyIndex dpindex=new TcompanyIndex();
			dpindex.setTindexTarget(new TindexTarget(indexID));
			dpindex.setAct_output(dpelem.getAct_output());
			dpindex.setPercentage(dpelem.getPercentage());
			dpindex.setScore(dpelem.getScore());
			dpindex.setTdepartment(dpelem.getTdepartment());
			newDpIndexs.add(dpindex);
		}
		return newDpIndexs;
	}
	/**
	 * 通过empIndex转变成TcompanyIndex
	 * @param empIndex
	 * @return
	 */
	public static TcompanyIndex toTcompanyIndex(TempIndex empIndex){
		TcompanyIndex ci=new TcompanyIndex();
		ci.setScore(empIndex.getScore());
		ci.setAct_output(Float.parseFloat(empIndex.getAct_output()));
		ci.setTindexTarget(empIndex.getIndex());
		ci.setTdepartment(empIndex.getTempolyee().getTdepartment());
		return ci;
	}
}