package app.entity;

import java.util.HashSet;
import java.util.Set;

import common.util.MyUtil;

/**
 * Tdepartment generated by MyEclipse Persistence Tools
 */

public class Tdepartment implements java.io.Serializable {

	// Fields

	private Integer id;

	private String name;

	private String pmangerid;
	
	private String vaveUid;
	
	private String sonId;
	
	private Integer[] sons;

	private Set tempolyees = new HashSet(0);

	private Set tcompanyIndexes = new HashSet(0);

	private Set tusers = new HashSet(0);

	private Set totherSuggestions = new HashSet(0);

	private Set tmainSuggestions = new HashSet(0);

	// Constructors

	/** default constructor */
	public Tdepartment() {
	}

	/** minimal constructor */
	public Tdepartment(Integer id, String name) {
		this.id = id;
		this.name = name;
	}
	public Tdepartment( String name) {
		
		this.name = name;
	}
	public Tdepartment(Integer id) {
		this.id = id;
		//this.name = name;
	}
	/** full constructor */
	public Tdepartment(Integer id, String name, String pmangerid,
			Set tempolyees, Set tcompanyIndexes, Set tusers,
			Set totherSuggestions, Set tmainSuggestions) {
		this.id = id;
		this.name = name;
		this.pmangerid = pmangerid;
		this.tempolyees = tempolyees;
		this.tcompanyIndexes = tcompanyIndexes;
		this.tusers = tusers;
		this.totherSuggestions = totherSuggestions;
		this.tmainSuggestions = tmainSuggestions;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPmangerid() {
		return this.pmangerid;
	}

	public void setPmangerid(String pmangerid) {
		this.pmangerid = pmangerid;
	}

	public Set getTempolyees() {
		return this.tempolyees;
	}

	public void setTempolyees(Set tempolyees) {
		this.tempolyees = tempolyees;
	}

	public Set getTcompanyIndexes() {
		return this.tcompanyIndexes;
	}

	public void setTcompanyIndexes(Set tcompanyIndexes) {
		this.tcompanyIndexes = tcompanyIndexes;
	}

	public Set getTusers() {
		return this.tusers;
	}

	public void setTusers(Set tusers) {
		this.tusers = tusers;
	}

	public Set getTotherSuggestions() {
		return this.totherSuggestions;
	}

	public void setTotherSuggestions(Set totherSuggestions) {
		this.totherSuggestions = totherSuggestions;
	}

	public Set getTmainSuggestions() {
		return this.tmainSuggestions;
	}

	public void setTmainSuggestions(Set tmainSuggestions) {
		this.tmainSuggestions = tmainSuggestions;
	}

	public String getVaveUid() {
		return vaveUid;
	}

	public void setVaveUid(String vaveUid) {
		this.vaveUid = vaveUid;
	}

	public String getSonId() {
		return sonId;
	}

	public void setSonId(String sonId) {
		this.sonId = sonId;
	}

	public Integer[] getSons() {
		String temps=sonId+","+id;
		if(sonId==null||sonId.equals(""))
		{
			temps=id+"";
		}
		return MyUtil.toTransFormInteger(temps.split(","));
	}

}