package app.entity;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import net.sf.json.JSONString;

/**
 * TempIndexId generated by MyEclipse Persistence Tools
 */

public class TempIndex extends Index implements java.io.Serializable,JSONString {

	// Fields

	private Tempolyee tempolyee=new Tempolyee();

	private TindexTarget index=new TindexTarget();

	private Float score;

	private Float percentage;
	
	private Integer id;
	
	private String act_output;
	
	// Constructors

	/** default constructor */
	public TempIndex() {
	}

	/** minimal constructor */
	public TempIndex(Tempolyee uid, TindexTarget indexId) {
		this.tempolyee = uid;
		this.index = indexId;
	}

	/** full constructor */
	public TempIndex(Tempolyee uid, TindexTarget indexId, Float score,
			Float percentage) {
		this.tempolyee = uid;
		this.index = indexId;
		this.score = score;
		this.percentage = percentage;
	}

	// Property accessors





	public Float getScore() {
		return this.score;
	}

	public void setScore(Float score) {
		this.score = score;
	}

	public Float getPercentage() {
		return this.percentage;
	}

	public void setPercentage(Float percentage) {
		this.percentage = percentage;
	}

	public Tempolyee getTempolyee() {
		return tempolyee;
	}

	public void setTempolyee(Tempolyee tempolyee) {
		this.tempolyee = tempolyee;
	}

	public TindexTarget getIndex() {
		return index;
	}

	public void setIndex(TindexTarget index) {
		this.index = index;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getAct_output() {
		DecimalFormat   df   =   new   DecimalFormat("#.0000");   
		if(act_output != null && !"".equals(act_output)&& !"null".equals(act_output)) {
			return df.format(Float.parseFloat(act_output));
		} else {
			return "";
		}
	}

	public void setAct_output(String act_output) {
		this.act_output = act_output;
	}

	public static List<TempIndex> copyChangeIndex(List<TempIndex> empIndexs,Integer indexID )
	{
		List<TempIndex> newEmpIndexs=new ArrayList<TempIndex>();
		for(TempIndex empElem:empIndexs)
		{
			TempIndex eindex=new TempIndex();
			eindex.setIndex(new TindexTarget(indexID));
			eindex.setAct_output(empElem.getAct_output());
			eindex.setPercentage(empElem.getPercentage());
			eindex.setScore(empElem.getScore());
			eindex.setTempolyee(empElem.getTempolyee());
			newEmpIndexs.add(eindex);
		}
		return newEmpIndexs;
	}

	public String toJSONString() {
		// TODO Auto-generated method stub
		return  index.toJSONString();
	}

}