package app.entity;

import java.util.HashSet;
import java.util.Set;

import net.sf.json.JSONString;

/**
 * TindexTarget generated by MyEclipse Persistence Tools
 */

public class TindexTarget implements java.io.Serializable,JSONString {

	// Fields


	private Integer id;
	
	private String name;

	private String type;
	
	private String isChoice;// 必选，可选，必选且权重不可变
	
	private String a;
	private String b;
	private String c;	
	private String formula;

	private Set tcompanyIndexes = new HashSet(0);
	
	private Set empIndexs=new HashSet(0);
	
	private Integer departID;// 1 stand for company,2 hr,3 PM
	
	private String version;
	
	private String isReadOnly; //显示是否可以修改
	private int isAll;     //是否为全部修改,1 is all,0 is single
	// Constructors



	public String getIsReadOnly() {
		if(type.equals("非量化指标")){
			return "white";
		}else{
			return "gray";
		}
		
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public Integer getDepartID() {
		return departID;
	}

	public void setDepartID(Integer departID) {
		this.departID = departID;
	}

	/** default constructor */
	public TindexTarget() {
	}

	public TindexTarget(Integer id) {
		this.id=id;
	}

	/** full constructor */
	public TindexTarget(String name, String type, Set tcompanyIndexes) {
	
		this.name = name;
		this.type = type;
	
		this.tcompanyIndexes = tcompanyIndexes;
	}

	// Property accessors

	

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}



	public Set getTcompanyIndexes() {
		return this.tcompanyIndexes;
	}

	public void setTcompanyIndexes(Set tcompanyIndexes) {
		this.tcompanyIndexes = tcompanyIndexes;
	}


	public String getIsChoice() {
		return isChoice;
	}

	public void setIsChoice(String isChoice) {
		this.isChoice = isChoice;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFormula() {
		return formula;
	}

	public void setFormula(String formula) {
		this.formula = formula;
	}

	public Set getEmpIndexs() {
		return empIndexs;
	}

	public void setEmpIndexs(Set empIndexs) {
		this.empIndexs = empIndexs;
	}

	public String getA() {
		return a;
	}

	public void setA(String a) {
		this.a = a;
	}

	public String getB() {
		return b;
	}

	public void setB(String b) {
		this.b = b;
	}

	public String getC() {
		return c;
	}

	public void setC(String c) {
		this.c = c;
	}

	public static Float cal(TindexTarget item,Float output)
	{
		Float score=0f;
		if(!item.getType().equals("非量化指标"))
		{
			Float a=Float.parseFloat(item.getA());
			Float b=Float.parseFloat(item.getB());
			Float c=Float.parseFloat(item.getC());
			if(a>output)
			{
				return score;
			}
			if(output>=a&&output<b)
			{
				score=(30/(b-a))*output+(70-(30*a/(b-a)));
				return score;
			}
			if(output>=b&&output<c)
			{
				
				score=(50/(c-b))*output+(100-(50*b/(c-b)));
				return score;
			}
			if(output>=c)
			{
				score=150f;
				return score;
			}
		}
		return score;
	}

	public int getIsAll() {
		return isAll;
	}

	public void setIsAll(int isAll) {
		this.isAll = isAll;
	}
	/**
	 * 全部设值
	 */
	public void setAll(TindexTarget index){
		setA(index.getA());
		setB(index.getB());
		setC(index.getC());
		setName(index.getName());
		setDepartID(index.getDepartID());
		setFormula(index.getFormula());
		setVersion(index.getVersion());
	}

	public String toJSONString() {
		// TODO Auto-generated method stub
		return "{name:'"+name.replace('\n', ' ')+"',type:'"+type+"',formula:'"+formula
				+"',a:'"+a+"',b:'"+b+"',c:'"+c+"',id:'"+id+"'}";
	}

}