package app.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TmainSuggestion generated by MyEclipse Persistence Tools
 */

public class TmainSuggestion implements java.io.Serializable {

	// Fields

	private Integer id;

	private Tproposal tproposal=new Tproposal();

	private String suggestionType;

	private String implementationPartment;

	private String isApproval;

	private Date suggestionDate;

	private Integer departmentId;
	
	private String suggest_context;
	
	private String approved_Name;
	
	private String implement_departmentName;

	private Set totherSuggestions = new HashSet(0);

	// Constructors

	/** default constructor */
	public TmainSuggestion() {
	}

	/** minimal constructor */
	public TmainSuggestion(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public TmainSuggestion(Integer id, Tproposal tproposal,
			String suggestionType, String implementationPartment,
			String isApproval, Date suggestionDate, Integer departmentId,
			Set totherSuggestions) {
		this.id = id;
		this.tproposal = tproposal;
		this.suggestionType = suggestionType;
		this.implementationPartment = implementationPartment;
		this.isApproval = isApproval;
		this.suggestionDate = suggestionDate;
		this.departmentId = departmentId;
		this.totherSuggestions = totherSuggestions;
	}

	// Property accessors



	public Tproposal getTproposal() {
		return this.tproposal;
	}

	public void setTproposal(Tproposal tproposal) {
		this.tproposal = tproposal;
	}



	public String getIsApproval() {
		return this.isApproval;
	}

	public void setIsApproval(String isApproval) {
		this.isApproval = isApproval;
	}

	public Date getSuggestionDate() {
		return this.suggestionDate;
	}

	public void setSuggestionDate(Date suggestionDate) {
		this.suggestionDate = suggestionDate;
	}

	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public Set getTotherSuggestions() {
		return this.totherSuggestions;
	}

	public void setTotherSuggestions(Set totherSuggestions) {
		this.totherSuggestions = totherSuggestions;
	}

	public String getImplementationPartment() {
		return implementationPartment;
	}

	public void setImplementationPartment(String implementationPartment) {
		this.implementationPartment = implementationPartment;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSuggestionType() {
		return suggestionType;
	}

	public void setSuggestionType(String suggestionType) {
		this.suggestionType = suggestionType;
	}

	public String getSuggest_context() {
		return suggest_context;
	}

	public void setSuggest_context(String suggest_context) {
		this.suggest_context = suggest_context;
	}

	public String getApproved_Name() {
		return approved_Name;
	}

	public void setApproved_Name(String approved_Name) {
		this.approved_Name = approved_Name;
	}

	public String getImplement_departmentName() {
		return implement_departmentName;
	}

	public void setImplement_departmentName(String implement_departmentName) {
		this.implement_departmentName = implement_departmentName;
	}

}