package app.entity;

import java.util.Date;

/**
 * TotherSuggestion generated by MyEclipse Persistence Tools
 */

public class TotherSuggestion implements java.io.Serializable {

	// Fields

	private Integer id;

	private TmainSuggestion tmainSuggestion=new TmainSuggestion();

	private String suggestionType;

	private Integer isApproval;

	private Date suggestionDate;

	private Integer departmentId;
	
	private String departmentName;
	
	private String approveName;
	
	private String suggest_context;
	
	private Tproposal tproposal=new Tproposal();

	// Constructors

	/** default constructor */
	public TotherSuggestion() {
	}

	/** minimal constructor */
	public TotherSuggestion(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public TotherSuggestion(Integer id, TmainSuggestion tmainSuggestion,
			String suggestionType, Integer isApproval, Date suggestionDate,
			Integer departmentId) {
		this.id = id;
		this.tmainSuggestion = tmainSuggestion;
		this.suggestionType = suggestionType;
		this.isApproval = isApproval;
		this.suggestionDate = suggestionDate;
		this.departmentId = departmentId;
	}

	// Property accessors



	public TmainSuggestion getTmainSuggestion() {
		return this.tmainSuggestion;
	}

	public void setTmainSuggestion(TmainSuggestion tmainSuggestion) {
		this.tmainSuggestion = tmainSuggestion;
	}



	public Integer getIsApproval() {
		return this.isApproval;
	}

	public void setIsApproval(Integer isApproval) {
		this.isApproval = isApproval;
	}

	public Date getSuggestionDate() {
		return this.suggestionDate;
	}

	public void setSuggestionDate(Date suggestionDate) {
		this.suggestionDate = suggestionDate;
	}

	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSuggestionType() {
		return suggestionType;
	}

	public void setSuggestionType(String suggestionType) {
		this.suggestionType = suggestionType;
	}

	public Tproposal getTproposal() {
		return tproposal;
	}

	public void setTproposal(Tproposal tproposal) {
		this.tproposal = tproposal;
	}

	public String getSuggest_context() {
		return suggest_context;
	}

	public void setSuggest_context(String suggest_context) {
		this.suggest_context = suggest_context;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getApproveName() {
		return approveName;
	}

	public void setApproveName(String approveName) {
		this.approveName = approveName;
	}

}