package app.entity;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TpostType generated by MyEclipse Persistence Tools
 */

public class TpostType implements java.io.Serializable {

	// Fields

	private String type;

	private Float maxValue;

	private Float minValue;

	private Float midValue;//70%
	
	private Float thrity;//30%

	private Set tposts = new HashSet(0);
	
	//计算岗位工资等级
	public  static void calSalaryType(List<TpostType> list,Tempolyee item)
	{
		 for (TpostType type : list) {
				if( item.getBaseSalary()<= type.getMaxValue()&& item.getBaseSalary()>=type.getMinValue())
				{
					item.setSalaryType(type.getType());
				}
			}
	}
	// Constructors

	/** default constructor */
	public TpostType() {
	}

	/** minimal constructor */
	public TpostType(String type) {
		this.type = type;
	}

	/** full constructor */
	public TpostType(String type, Float maxValue, Float minValue,
			Float midValue, Set tposts) {
		this.type = type;
		this.maxValue = maxValue;
		this.minValue = minValue;
		this.midValue = midValue;
		this.tposts = tposts;
	}

	// Property accessors

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Float getMaxValue() {
		return this.maxValue;
	}

	public void setMaxValue(Float maxValue) {
		this.maxValue = maxValue;
	}

	public Float getMinValue() {
		return this.minValue;
	}

	public void setMinValue(Float minValue) {
		this.minValue = minValue;
	}

	public Float getMidValue() {
		return this.midValue;
	}

	public void setMidValue(Float midValue) {
		this.midValue = midValue;
	}

	public Set getTposts() {
		return this.tposts;
	}

	public void setTposts(Set tposts) {
		this.tposts = tposts;
	}

	public Float getThrity() {
		return thrity;
	}

	public void setThrity(Float thrity) {
		this.thrity = thrity;
	}

}