package app.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tpost generated by MyEclipse Persistence Tools
 */

public class Tpost implements java.io.Serializable {

	// Fields

	private String id;

	private TpostType tpostType=new TpostType();

	private String productName;

	private Integer type;

	private Set temployeeProducts = new HashSet(0);
	
	public static int Tpost_PostSalary=1;
	public static int Tpost_Bounce=2;

	// Constructors

	/** default constructor */
	public Tpost() {
	}
	
	public Tpost(String id) {
		this.id = id;
	}
	
	/** minimal constructor */
	public Tpost(String id, TpostType tpostType) {
		this.id = id;
		this.tpostType = tpostType;
	}

	/** full constructor */
	public Tpost(String id, TpostType tpostType, String productName,	
			Set temployeeProducts) {
		this.id = id;
		this.tpostType = tpostType;
		this.productName = productName;
		this.temployeeProducts = temployeeProducts;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public TpostType getTpostType() {
		return this.tpostType;
	}

	public void setTpostType(TpostType tpostType) {
		this.tpostType = tpostType;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Set getTemployeeProducts() {
		return this.temployeeProducts;
	}

	public void setTemployeeProducts(Set temployeeProducts) {
		this.temployeeProducts = temployeeProducts;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}