package app.entity;

/**
 * TpostId generated by MyEclipse Persistence Tools
 */

public class TpostId implements java.io.Serializable {

	// Fields

	private Integer id;

	private String firstName;

	private String midName;

	private String lastName;

	// Constructors

	/** default constructor */
	public TpostId() {
	}

	/** full constructor */
	public TpostId(String firstName, String midName, String lastName) {
		this.firstName = firstName;
		this.midName = midName;
		this.lastName = lastName;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMidName() {
		return this.midName;
	}

	public void setMidName(String midName) {
		this.midName = midName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

}