package app.entity;

/**
 * Tprogram generated by MyEclipse Persistence Tools
 */

public class Tprogram implements java.io.Serializable {

	// Fields

	private Integer id;

	private Ttheme ttheme=new Ttheme();

	private String insteadProgram;

	// Constructors

	/** default constructor */
	public Tprogram() {
	}

	/** minimal constructor */
	public Tprogram(Integer themeId, Ttheme ttheme) {
	
		this.ttheme = ttheme;
	}

	/** full constructor */
	public Tprogram(Integer id, Ttheme ttheme, String insteadProgram) {
		this.id = id;
		this.ttheme = ttheme;
		this.insteadProgram = insteadProgram;
	}

	// Property accessors



	public Ttheme getTtheme() {
		return this.ttheme;
	}

	public void setTtheme(Ttheme ttheme) {
		this.ttheme = ttheme;
	}

	public String getInsteadProgram() {
		return this.insteadProgram;
	}

	public void setInsteadProgram(String insteadProgram) {
		this.insteadProgram = insteadProgram;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	

}