package app.entity;

import java.util.HashSet;
import java.util.Set;

/**
 * Ttheme generated by MyEclipse Persistence Tools
 */

public class Ttheme implements java.io.Serializable {

	// Fields

	private Integer id;

	private Tproposal tproposal=new Tproposal();

	private String partsName;

	private String partsId;

	private String customer;

	private String applicableModels;

	private Float systemAnnualOutputs;

	private Float partsAnnualOutputs;

	private String company;


	private Set tprojectTeams = new HashSet(0);

	private Set tprograms = new HashSet(0);

	// Constructors

	/** default constructor */
	public Ttheme() {
	}

	/** full constructor */
	public Ttheme(Tproposal tproposal, String partsName, Integer partsId,
			String customer, String applicableModels,
			Float systemAnnualOutputs, Float partsAnnualOutputs,
			String company, Set tprojectTeams, Set tprograms) {
		this.tproposal = tproposal;
		this.partsName = partsName;

		this.customer = customer;
		this.applicableModels = applicableModels;
		this.systemAnnualOutputs = systemAnnualOutputs;
		this.partsAnnualOutputs = partsAnnualOutputs;
		this.company = company;
	
		this.tprojectTeams = tprojectTeams;
		this.tprograms = tprograms;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tproposal getTproposal() {
		return this.tproposal;
	}

	public void setTproposal(Tproposal tproposal) {
		this.tproposal = tproposal;
	}

	public String getPartsName() {
		return this.partsName;
	}

	public void setPartsName(String partsName) {
		this.partsName = partsName;
	}



	public String getCustomer() {
		return this.customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	public String getApplicableModels() {
		return this.applicableModels;
	}

	public void setApplicableModels(String applicableModels) {
		this.applicableModels = applicableModels;
	}

	public Float getSystemAnnualOutputs() {
		return this.systemAnnualOutputs;
	}

	public void setSystemAnnualOutputs(Float systemAnnualOutputs) {
		this.systemAnnualOutputs = systemAnnualOutputs;
	}

	public Float getPartsAnnualOutputs() {
		return this.partsAnnualOutputs;
	}

	public void setPartsAnnualOutputs(Float partsAnnualOutputs) {
		this.partsAnnualOutputs = partsAnnualOutputs;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}


	public Set getTprojectTeams() {
		return this.tprojectTeams;
	}

	public void setTprojectTeams(Set tprojectTeams) {
		this.tprojectTeams = tprojectTeams;
	}

	public Set getTprograms() {
		return this.tprograms;
	}

	public void setTprograms(Set tprograms) {
		this.tprograms = tprograms;
	}

	public String getPartsId() {
		return partsId;
	}

	public void setPartsId(String partsId) {
		this.partsId = partsId;
	}



}