package app.entity;

import org.springframework.security.GrantedAuthority;
import org.springframework.security.userdetails.UserDetails;

import common.entity.TuserRole;

/**
 * Tuser generated by MyEclipse Persistence Tools
 */

public class Tuser implements java.io.Serializable ,UserDetails{

	// Fields

	private String uid;
	
	private String userName;
	private String passWD;
	
	private TuserRole userRole=new TuserRole();

	private Integer rights;

	//private Integer departmentid;
	
	private Tempolyee emp=new Tempolyee();

	// Constructors

	/** default constructor */
	public Tuser() {
	}

	/** minimal constructor */
	public Tuser(String uid, Integer rights) {
		this.uid = uid;
		this.rights = rights;
	}

	/** full constructor */
	public Tuser(String uid, TuserRole trole, Integer rights, Integer departmentid) {
		this.uid = uid;
		this.userRole = trole;
		this.rights = rights;
		//this.departmentid = departmentid;
	}

	// Property accessors

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}


	public Integer getRights() {
		return this.rights;
	}

	public void setRights(Integer rights) {
		this.rights = rights;
	}

	public Tempolyee getEmp() {
		return emp;
	}

	public void setEmp(Tempolyee emp) {
		this.emp = emp;
	}

	public GrantedAuthority[] getAuthorities() {
		// TODO 自动生成方法存根
		return null;
	}

	public String getPassword() {
		// TODO 自动生成方法存根
		return null;
	}

	public String getUsername() {
		// TODO 自动生成方法存根
		return null;
	}

	public boolean isAccountNonExpired() {
		// TODO 自动生成方法存根
		return false;
	}

	public boolean isAccountNonLocked() {
		// TODO 自动生成方法存根
		return false;
	}

	public boolean isCredentialsNonExpired() {
		// TODO 自动生成方法存根
		return false;
	}

	public boolean isEnabled() {
		// TODO 自动生成方法存根
		return false;
	}

	public TuserRole getUserRole() {
		return userRole;
	}

	public void setUserRole(TuserRole userRole) {
		this.userRole = userRole;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassWD() {
		return passWD;
	}

	public void setPassWD(String passWD) {
		this.passWD = passWD;
	}



}