/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.action.vave;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import sdaac.wym.app.entity.vave.BusinessTopic;

import app.entity.Tuser;
import app.web.struts.action.BaseAction;
import app.web.struts.form.vave.BusinessTopicForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2010
 * 
 * XDoclet definition:
 * @struts.action path="/businessTopic" name="businessTopicForm" input="/form/businessTopic.jsp" parameter="actionType" scope="request" validate="true"
 * 经验课题
 */
public class BusinessTopicAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 查询自己发布的
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward doSelectMyself(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {	
		Tuser user=(Tuser)request.getSession().getAttribute("logineduser");
		BusinessTopic bt = new BusinessTopic(); 
		bt.setPublisher(user.getEmp());
		request.setAttribute("rs", this.getBusinessTopicManager().showMyRelease(bt)) ;
		return mapping.findForward("myTopicList");
	}
	
	/**
	 * 发布
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward release(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BusinessTopicForm businessTopicForm = (BusinessTopicForm) form;// TODO Auto-generated method stub
		this.getBusinessTopicManager().release(businessTopicForm.getBt());
		return mapping.findForward("business");
	}
	
	/**
	 * 查询单个经营主题
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward doSelectDetails(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int id = Integer.parseInt(request.getParameter("id"));
	//	BusinessTopicForm businessTopicForm = (BusinessTopicForm) form;// TODO Auto-generated method stub
		 List<BusinessTopic> rs = this.getBusinessTopicManager().show(new BusinessTopic(id));
		request.setAttribute("rs",rs.get(0));
		if(request.getParameter("flagSelect")!=null){
			return mapping.findForward("showBusiness");
		}else{
			return mapping.findForward("updateBusiness");
		}
		
	}
	
	/**
	 * 更新
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BusinessTopicForm businessTopicForm = (BusinessTopicForm) form;// TODO Auto-generated method stub
		this.getBusinessTopicManager().update(businessTopicForm.getBt());
		return mapping.findForward("business");
	}
	
	/**
	 * 删除
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward doDelete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {	
		int id = Integer.parseInt(request.getParameter("id"));
		this.getBusinessTopicManager().doDelete(id);
		return mapping.findForward("myTopicList");
	}
	
	/**
	 * 查询
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward doSelect(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {	
	//	Tuser user=(Tuser)request.getSession().getAttribute("logineduser");
		BusinessTopic bt = new BusinessTopic(); 
		request.setAttribute("rs", this.getBusinessTopicManager().doSelect(bt)) ;
		return mapping.findForward("topicList");
	}
}