/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.action.vave;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-17-2010
 * 
 * XDoclet definition:
 * @struts.action path="/goods" name="goodsForm" input="/form/goods.jsp" parameter="actionType" scope="request" validate="true"
 */
public class GoodsAction extends VaveGoodsBaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 显示所有纪念品
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward showAll(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//GoodsForm goodsForm = (GoodsForm) form;// TODO Auto-generated method stub
		request.setAttribute("rs",  this.getGoodsManager().show());
		return mapping.findForward("goodsList");
	}
	
	/** 
	 * 显示单个纪念品
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward showDetails(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//GoodsForm goodsForm = (GoodsForm) form;// TODO Auto-generated method stub
		int goodsId =Integer.parseInt(request.getParameter("goodsId"));
		request.setAttribute("rs",  this.getGoodsManager().showDetails(goodsId));
		return mapping.findForward("goodsDetails");
	}
}