/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.action.pcl.maindata;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import sdaac.wym.app.Service.PCL.MainData.ApproveForm;
import sdaac.wym.app.Service.PCL.MainData.MDForm;


/** 
 * MyEclipse Struts
 * Creation date: 06-10-2011
 * 
 * XDoclet definition:
 * @struts.form name="labActionForm"
 */
public class MainDataForm extends ActionForm {
	
	private MDForm form = new MDForm();
	private ApproveForm apForm = new ApproveForm();
	private FormFile formFile;
	private FormFile file2;
	private FormFile file3;

	public FormFile getFormFile() {
		return formFile;
	}

	public void setFormFile(FormFile formFile) {
		this.formFile = formFile;
	}

	public FormFile getFile2() {
		return file2;
	}

	public void setFile2(FormFile file2) {
		this.file2 = file2;
	}

	public FormFile getFile3() {
		return file3;
	}

	public void setFile3(FormFile file3) {
		this.file3 = file3;
	}

	public ApproveForm getApForm() {
		return apForm;
	}

	public void setApForm(ApproveForm apForm) {
		this.apForm = apForm;
	}

	public MDForm getForm() {
		return form;
	}

	public void setForm(MDForm form) {
		this.form = form;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

}