/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.form.vave;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import sdaac.wym.app.entity.vave.Account;
import sdaac.wym.app.entity.vave.AccountGoods;

/** 
 * MyEclipse Struts
 * Creation date: 03-16-2010
 * 
 * XDoclet definition:
 * @struts.form name="accountForm"
 */
public class AccountForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private AccountGoods ag = new AccountGoods();
	public AccountGoods getAg() {
		return ag;
	}

	public void setAg(AccountGoods ag) {
		this.ag = ag;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}