/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.web.struts.DispatchActionSupport;

import sdaac.wym.app.Service.audit.AuditManager;
import sdaac.wym.app.Service.plm.PlmManager;

import app.web.struts.form.AuditForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2009
 * 
 * XDoclet definition:
 * @struts.action path="/audit" name="auditForm" input="/form/audit.jsp" parameter="actionType" scope="request" validate="true"
 */
public class AuditAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 查询每日信息表
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward select(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AuditForm auditForm = (AuditForm) form;// TODO Auto-generated method stub	
		request.setAttribute("rs", this.getAuditDailyBizImpl().select(auditForm.getAudit()));
		return mapping.findForward("auditManager");
	}

}