/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.action;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.jdom.JDOMException;

import sdaac.wym.app.entity.News.CatagoryItem;

import common.util.XmlParse;

import app.web.struts.form.MenuForm;

/** 
 * MyEclipse Struts
 * Creation date: 12-03-2009
 * 
 * XDoclet definition:
 * @struts.action path="/menu" name="menuForm" input="/form/menu.jsp" parameter="actionType" scope="request" validate="true"
 */
public class MenuAction extends org.springframework.web.struts.DispatchActionSupport {
	/*
	 * Generated Methods
	 */

	/** 
	 * 处理菜单xml
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException 
	 * @throws JDOMException 
	 */
	public ActionForward deal(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws JDOMException, IOException {
		MenuForm menuForm = (MenuForm) form;// TODO Auto-generated method stub
		CatagoryItem item= menuForm.getItem();
		
		if(item.getMethod().equals("modify")){		
			XmlParse xml=new XmlParse(item);
			xml.update();
		}else if(item.getMethod().equals("add")){
			item.setPid(item.getPid());
			XmlParse xml=new XmlParse(item);
			xml.add();
		}
//		if(item.getMethod().equals("delete")){
//			XmlParse xml=new XmlParse(item);
//			xml.delete();
//		}
		
		response.getWriter().print("<h3>ok</h3>");
		return null;
	}
}