/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import app.web.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-15-2009
 * 
 * XDoclet definition:
 * @struts.action parameter="actionType" validate="true"
 */
public class UserAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward doInsert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		UserForm userForm=(UserForm)form;
		String uid=userForm.getItem().getUid();
		Integer rights=userForm.getItem().getRights();
	//	String uid=(String) request.getAttribute("uid");
	//	Integer rights=Integer.parseInt(request.getParameter("rights"));
		this.getUserBiz().doInsert(uid, rights);
		return mapping.findForward("success");
	}
}