/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import sdaac.wym.app.entity.audit.WinAudi2;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2009
 * 
 * XDoclet definition:
 * @struts.form name="auditForm"
 */
public class AuditForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	
	private WinAudi2 audit=new WinAudi2();
	
	public WinAudi2 getAudit() {
		return audit;
	}

	public void setAudit(WinAudi2 audit) {
		this.audit = audit;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}