/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.form;


import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import app.entity.vave.VaveCompanySuggestion;
import app.entity.vave.VaveTeamWork;
import app.entity.vave.VaveTeamWorkProject;
import java.util.List;
import common.util.AutoArrayList;
import java.util.ArrayList;
import common.util.MyUtil;
/** 
 * MyEclipse Struts
 * Creation date: 03-19-2009
 * 
 * XDoclet definition:
 * @struts.form name="companySuggestionForm"
 */
public class CompanySuggestionForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	private VaveCompanySuggestion companySug=new VaveCompanySuggestion();
	private VaveTeamWork teamWork=new VaveTeamWork();
//	private VaveTeamWorkProject teamWorkProject=new VaveTeamWorkProject();
	private List<VaveTeamWorkProject> teamWorkProject=new AutoArrayList(VaveTeamWorkProject.class);
	//private List list=new List();
	//private List<String> planTimes=new AutoArrayList(String.class);
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public VaveCompanySuggestion getCompanySug() {
		return companySug;
	}

	public void setCompanySug(VaveCompanySuggestion companySug) {
		this.companySug = companySug;
	}

	public VaveTeamWork getTeamWork() {
		return teamWork;
	}

	public void setTeamWork(VaveTeamWork teamWork) {
		this.teamWork = teamWork;
	}

	public List<VaveTeamWorkProject> getTeamWorkProject() {
		return teamWorkProject;
	}

	public void setTeamWorkProject(List<VaveTeamWorkProject> teamWorkProject) {
		this.teamWorkProject.clear();
		this.teamWorkProject.addAll(teamWorkProject);
	}
}