/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import common.util.AutoArrayList;

import app.entity.TcompanyIndex;

import java.util.List;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2009
 * 
 * XDoclet definition:
 * @struts.form name="departIndexForm"
 */
public class DepartIndexForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	private List<TcompanyIndex> items=new AutoArrayList(TcompanyIndex.class);
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public List<TcompanyIndex> getItems() {
		return items;
	}

	public void setItems(List<TcompanyIndex> items) {
		//this.items = items;
		this.items.clear();
		this.items.addAll(items);
	}
}