/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.form;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import java.util.List;
import app.entity.TempIndex;
import common.util.AutoArrayList;

/** 
 * MyEclipse Struts
 * Creation date: 03-11-2009
 * 
 * XDoclet definition:
 * @struts.form name="empIndexForm"
 */
public class EmpIndexForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	private List<TempIndex> items= new AutoArrayList(TempIndex.class);
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param 
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public List<TempIndex> getItems() {
		return items;
	}

	public void setItems(List<TempIndex> items) {
		items.clear();
		items.addAll(items);
	}

	
}