/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import common.util.AutoArrayList;

import sdaac.wym.app.entity.hr.BounceFigure;
import sdaac.wym.app.entity.hr.BouncePost;

/** 
 * MyEclipse Struts
 * Creation date: 07-03-2009
 * 
 * XDoclet definition:
 * @struts.form name="figureAndPostIdForm"
 */
public class FigureAndPostIdForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	private FormFile formFile;
	private BounceFigure bf=new BounceFigure();
	private BouncePost bp=new BouncePost();
	private List<BounceFigure> bfs=new AutoArrayList(BounceFigure.class);
	
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public BounceFigure getBf() {
		return bf;
	}

	public void setBf(BounceFigure bf) {
		this.bf = bf;
	}

	public BouncePost getBp() {
		return bp;
	}

	public void setBp(BouncePost bp) {
		this.bp = bp;
	}

	public List<BounceFigure> getBfs() {
		return bfs;
	}

	public void setBfs(List<BounceFigure> bfs) {
		this.bfs.clear();
		this.bfs.addAll(bfs);
	}

	public FormFile getFormFile() {
		return formFile;
	}

	public void setFormFile(FormFile formFile) {
		this.formFile = formFile;
	}
}