/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.form;

import java.io.UnsupportedEncodingException;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import common.util.AutoArrayList;

import app.entity.TemployeeProduct;
import app.entity.TindexTarget;

/** 
 * MyEclipse Struts
 * Creation date: 01-24-2009
 * 
 * XDoclet definition:
 * @struts.form name="indexForm"
 */
public class IndexForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private TindexTarget item=new TindexTarget();
	private List<TindexTarget> items=new AutoArrayList(TindexTarget.class);
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		try {
			request.setCharacterEncoding("utf-8");
		} catch (UnsupportedEncodingException e) {}
	}

	public TindexTarget getItem() {
		return item;
	}

	public void setItem(TindexTarget item) {
		this.item = item;
	}

	public List<TindexTarget> getItems() {
		return items;
	}

	public void setItems(List<TindexTarget> items) {
		//this.items = items;
		this.items.clear();
		this.items.addAll(items);
	}
}