/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import sdaac.wym.app.entity.News.CatagoryItem;

/** 
 * MyEclipse Struts
 * Creation date: 12-03-2009
 * 
 * XDoclet definition:
 * @struts.form name="menuForm"
 */
public class MenuForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private CatagoryItem item=new CatagoryItem();
	public CatagoryItem getItem() {
		return item;
	}

	public void setItem(CatagoryItem item) {
		this.item = item;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}