/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.form;


import java.util.List;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import common.util.AutoArrayList;

import app.entity.TemployeeProduct;

/** 
 * MyEclipse Struts
 * Creation date: 12-22-2008
 * 
 * XDoclet definition:
 * @struts.form name="personalForm"
 */
public class PersonalForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	private List  items=new AutoArrayList(TemployeeProduct.class);
	private TemployeeProduct item=new TemployeeProduct();	
	private String productName=null;
	private String masterid;
	private String time;
	private String endTime;
	private String uname=null;
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		
	}


	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}



	public TemployeeProduct getItem() {
		return item;
	}

	public void setItem(TemployeeProduct item) {
		this.item = item;
	}

	public List getItems() {
		return items;
	}

	public void setItems(List items) {
		
	System.out.print(items.size());
		this.items.clear();
		this.items.addAll(items);
	}

	public String getMasterid() {
		return masterid;
	}

	public void setMasterid(String masterid) {
		this.masterid = masterid;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}







}