/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import common.util.AutoArrayList;

import app.entity.vave.VaveTeamWork;
import app.entity.vave.VaveTeamWorkProject;

/** 
 * MyEclipse Struts
 * Creation date: 03-19-2009
 * 
 * XDoclet definition:
 * @struts.form name="taskForm"
 */
public class TaskForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	private VaveTeamWorkProject teamWorkProject=new VaveTeamWorkProject();
	private VaveTeamWork teamWork=new VaveTeamWork();
	private List teamWorkProjectList=new AutoArrayList(VaveTeamWorkProject.class);
	private List teamWorkList=new AutoArrayList(VaveTeamWork.class);
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}



	public VaveTeamWork getTeamWork() {
		return teamWork;
	}

	public void setTeamWork(VaveTeamWork teamWork) {
		this.teamWork = teamWork;
	}

	public VaveTeamWorkProject getTeamWorkProject() {
		return teamWorkProject;
	}

	public void setTeamWorkProject(VaveTeamWorkProject teamWorkProject) {
		this.teamWorkProject = teamWorkProject;
	}

	public List getTeamWorkProjectList() {
		return teamWorkProjectList;
	}

	public void setTeamWorkProjectList(List teamWorkProjectList) {
		this.teamWorkProjectList.clear();
		this.teamWorkProjectList.addAll(teamWorkProjectList);
	}

	public List getTeamWorkList() {
		return teamWorkList;
	}

	public void setTeamWorkList(List teamWorkList) {
		this.teamWorkList.clear();
		this.teamWorkList.addAll(teamWorkList);
	}


}