/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package app.web.struts.action.lab;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import sdaac.wym.app.entity.lab.*;

/** 
 * MyEclipse Struts
 * Creation date: 06-10-2011
 * 
 * XDoclet definition:
 * @struts.form name="labActionForm"
 */
public class LabActionForm extends ActionForm {
	
	private LabForm item1;
	private LabInnerForm item = new LabInnerForm();
	private LabOutsideForm item2 = new LabOutsideForm();
	private ApproveForm approveFrom = new ApproveForm();
	
	public ApproveForm getApproveFrom() {
		return approveFrom;
	}

	public void setApproveFrom(ApproveForm approveFrom) {
		this.approveFrom = approveFrom;
	}

	public LabForm getItem1() {
		return item1;
	}

	public void setItem1(LabForm item1) {
		this.item1 = item1;
	}

	public LabInnerForm getItem() {
		return item;
	}

	public void setItem(LabInnerForm item) {
		this.item = item;
	}

	public LabOutsideForm getItem2() {
		return item2;
	}

	public void setItem2(LabOutsideForm item2) {
		this.item2 = item2;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

}